// Code generated by protoc-gen-go.
// source: dory.proto
// DO NOT EDIT!

/*
Package dory is a generated protocol buffer package.

It is generated from these files:
	dory.proto

It has these top-level messages:
	ValueType
	ReportLog
*/
package dory

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ValueType struct {
	IntType          *int32   `protobuf:"varint,1,opt,name=int_type,json=intType" json:"int_type,omitempty"`
	LongType         *int64   `protobuf:"varint,2,opt,name=long_type,json=longType" json:"long_type,omitempty"`
	FloatType        *float32 `protobuf:"fixed32,3,opt,name=float_type,json=floatType" json:"float_type,omitempty"`
	StringType       *string  `protobuf:"bytes,4,opt,name=string_type,json=stringType" json:"string_type,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ValueType) Reset()                    { *m = ValueType{} }
func (m *ValueType) String() string            { return proto.CompactTextString(m) }
func (*ValueType) ProtoMessage()               {}
func (*ValueType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ValueType) GetIntType() int32 {
	if m != nil && m.IntType != nil {
		return *m.IntType
	}
	return 0
}

func (m *ValueType) GetLongType() int64 {
	if m != nil && m.LongType != nil {
		return *m.LongType
	}
	return 0
}

func (m *ValueType) GetFloatType() float32 {
	if m != nil && m.FloatType != nil {
		return *m.FloatType
	}
	return 0
}

func (m *ValueType) GetStringType() string {
	if m != nil && m.StringType != nil {
		return *m.StringType
	}
	return ""
}

type ReportLog struct {
	LogTimestamp     *int64           `protobuf:"varint,1,req,name=log_timestamp,json=logTimestamp" json:"log_timestamp,omitempty"`
	Ip               *string          `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Field            *ReportLog_Field `protobuf:"group,3,opt,name=Field,json=field" json:"field,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ReportLog) Reset()                    { *m = ReportLog{} }
func (m *ReportLog) String() string            { return proto.CompactTextString(m) }
func (*ReportLog) ProtoMessage()               {}
func (*ReportLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReportLog) GetLogTimestamp() int64 {
	if m != nil && m.LogTimestamp != nil {
		return *m.LogTimestamp
	}
	return 0
}

func (m *ReportLog) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *ReportLog) GetField() *ReportLog_Field {
	if m != nil {
		return m.Field
	}
	return nil
}

type ReportLog_Field struct {
	Map              []*ReportLog_Field_Map `protobuf:"group,1,rep,name=Map,json=map" json:"map,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *ReportLog_Field) Reset()                    { *m = ReportLog_Field{} }
func (m *ReportLog_Field) String() string            { return proto.CompactTextString(m) }
func (*ReportLog_Field) ProtoMessage()               {}
func (*ReportLog_Field) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *ReportLog_Field) GetMap() []*ReportLog_Field_Map {
	if m != nil {
		return m.Map
	}
	return nil
}

type ReportLog_Field_Map struct {
	Key              *string    `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            *ValueType `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ReportLog_Field_Map) Reset()                    { *m = ReportLog_Field_Map{} }
func (m *ReportLog_Field_Map) String() string            { return proto.CompactTextString(m) }
func (*ReportLog_Field_Map) ProtoMessage()               {}
func (*ReportLog_Field_Map) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0, 0} }

func (m *ReportLog_Field_Map) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *ReportLog_Field_Map) GetValue() *ValueType {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*ValueType)(nil), "dory.ValueType")
	proto.RegisterType((*ReportLog)(nil), "dory.ReportLog")
	proto.RegisterType((*ReportLog_Field)(nil), "dory.ReportLog.Field")
	proto.RegisterType((*ReportLog_Field_Map)(nil), "dory.ReportLog.Field.Map")
}

func init() { proto.RegisterFile("dory.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x49, 0xd2, 0xc5, 0x66, 0xea, 0x3f, 0x02, 0x42, 0x5b, 0x11, 0x43, 0x45, 0x08, 0x14,
	0xf6, 0xb0, 0x1f, 0xc0, 0xa3, 0x27, 0x7b, 0x19, 0x8a, 0xd7, 0x12, 0x68, 0xba, 0x04, 0xb3, 0x9b,
	0xb0, 0x8d, 0xc2, 0x9e, 0xfd, 0xa8, 0x7e, 0x11, 0x49, 0x62, 0x7b, 0xf2, 0x36, 0xfb, 0x7e, 0xef,
	0xcd, 0x6c, 0x1e, 0xc0, 0xde, 0x0f, 0x63, 0x1d, 0x06, 0x1f, 0xbd, 0x98, 0xa4, 0x79, 0xf5, 0x4d,
	0x80, 0xbf, 0x6b, 0xf7, 0x69, 0xb6, 0x63, 0x30, 0x62, 0x01, 0x53, 0xdb, 0xc7, 0x5d, 0x1c, 0x83,
	0x99, 0x13, 0x49, 0x54, 0x85, 0x17, 0xb6, 0x8f, 0x19, 0xdd, 0x03, 0x77, 0xbe, 0x6f, 0x0b, 0xa3,
	0x92, 0x28, 0x86, 0xd3, 0x24, 0x64, 0xf8, 0x00, 0x70, 0x70, 0x5e, 0xff, 0x25, 0x99, 0x24, 0x8a,
	0x22, 0xcf, 0x4a, 0xc6, 0x8f, 0x30, 0x3b, 0xc6, 0xc1, 0x9e, 0xd2, 0x13, 0x49, 0x14, 0x47, 0x28,
	0x52, 0x32, 0xac, 0x7e, 0x08, 0x70, 0x34, 0xc1, 0x0f, 0xf1, 0xcd, 0xb7, 0xe2, 0x09, 0xae, 0x9c,
	0x6f, 0x77, 0xd1, 0x76, 0xe6, 0x18, 0x75, 0x17, 0xe6, 0x44, 0x52, 0xc5, 0xf0, 0xd2, 0xf9, 0x76,
	0x7b, 0xd2, 0xc4, 0x35, 0x50, 0x1b, 0xf2, 0x8f, 0x70, 0xa4, 0x36, 0x88, 0x35, 0x54, 0x07, 0x6b,
	0xdc, 0x3e, 0x5f, 0x87, 0xe6, 0xae, 0xce, 0x4f, 0x3d, 0x2f, 0xad, 0x5f, 0x13, 0xc4, 0xe2, 0x59,
	0x46, 0xa8, 0xf2, 0xb7, 0x58, 0x03, 0xeb, 0x74, 0x3a, 0xc0, 0x14, 0x34, 0x8b, 0x7f, 0x33, 0xf5,
	0x46, 0x07, 0x4c, 0xae, 0xe5, 0x0b, 0xb0, 0x8d, 0x0e, 0xe2, 0x16, 0xd8, 0x87, 0x19, 0x73, 0x3f,
	0x1c, 0xd3, 0x28, 0x9e, 0xa1, 0xfa, 0x4a, 0x1d, 0xce, 0xa9, 0xa4, 0x6a, 0xd6, 0xdc, 0x94, 0x3d,
	0xe7, 0x5a, 0xb1, 0xd0, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf3, 0xdc, 0x49, 0xf1, 0x7e, 0x01,
	0x00, 0x00,
}
